#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py migrate --verbosity 3

python manage.py collectstatic --noinput
exec uvicorn drf.asgi:application --host 0.0.0.0 --reload --reload-include '*.html'