version: '3'

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: drf_local_django
    container_name: drf_local_django
    depends_on:
      - mailhog
    ports:
      - "0.0.0.0:8000:8000"
    volumes:
      - .:/app
    command: /start
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"




