# Generated by Django 5.0.6 on 2024-05-23 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.nestedorganization'),
        ),
    ]
